spring:
  application:
  name: manager
  datasource:
#    url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:/home/sulabh/Documents/CDA/interview/Germany/AlephAlpha/springboot/manager/h2db/order
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update